
export  const courseOptions = [
  "Unknown",
    "BSc. Telecommunications Engineering",
    "BSc. Computer Engineering",
    "BS Mathematics",
    "BSc. Electrical and Electronic Engineering",
    "Diploma in Telecommunications Engineering",
    "Diploma in Information Technology",
    "BSc. Mobile Computing",
    "BSc. Computer Science",
    "BSc. Software Engineering",
    "BSc. Information Systems",
    "BSc. Data Science and Analytics",
    "Diploma in Data Science and Analytics",
    "Diploma in Information Technology",
    "Diploma in Cyber Security",
    "Diploma in Computer Science",
    "Diploma in Multimedia Technology",
    "Diploma in Web Application Development",
    "Business School",
    "BSc. Accounting with Computing",
    "BSc. Economics",
    "BSc. Procurement and Logistics",
    "BSc. Banking and Finance",
    "BSc. Business Administration",
    "Diploma in Public Relations",
    "Diploma in Management",
    "Diploma in Accounting",
    "Diploma in Marketing",

    // ...
  ];

  export const supervisorOptions = [
    "Unknown",
    "Abigail Wiafe",
    "Dr. Brenya Boahema",
    "Dr. Edward Boahen",
    "Dr. Eli Fianu",
    "Dr. Emmanuel Freeman",
    "Dr. Fred Amankwa",
    "Dr. Israel Edem Agbehadji",
    "Dr. Lempogo Forgor",
    "Dr. Martin Ujakpa",
    "Dr. Patrick Acheampong",
    "Dr. William Brown-Acquaye",
    "Mr. Bernard Appiah-Kubi",
    "Mr. Dominic K. Louis",
    "Mr. Dzordzoe Koffie-Ocloo",
    "Mr. Emmanuel M. Azadagli",
    "Mr. Eugene Badzangoly",
    "Mr. Frank Boateng",
    "Mr. George Kojo Anni",
    "Mr. Jonathan Kormi Korto",
    "Mr. Prince Kelvin Owusu",
    "Mr. Thomas Henaku",
    "Prof Alfred Coleman",
    "Prof. Kester Akphetsi",
    "Prof. Stephen Asunka",
    "Doreen Ampeh",
    "Christian Wogbe Biekro",
    "Mr. Daniel Anane",
    "Mr. George Asante",
    "Alexander Braye",
    "Veronica Agblewornu",

    // ...
  ];
